# Generated by Django 6.1.1 on 2026-09-12 06:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('teaching_status', models.CharField(blank=True, choices=[('lab_assistant', 'Лаборант'), ('senior_lab', 'Старший лаборант'), ('junior_teacher', 'Младший преподаватель'), ('teacher', 'Преподаватель'), ('senior_teacher', 'Старший преподаватель'), ('docent', 'Доцент'), ('professor', 'Профессор')], max_length=20, null=True, verbose_name='Преподавательский статус')),
                ('academic_degree', models.CharField(choices=[('none', 'Нет степени'), ('candidate', 'Кандидат наук'), ('doctor', 'Доктор наук')], default='none', max_length=20, verbose_name='Ученая степень')),
                ('position', models.CharField(choices=[('none', 'Нет административной должности'), ('head_of_department', 'Завкафедрой'), ('deputy_dean', 'Замдекана'), ('dean', 'Декан'), ('prorector', 'Проректор'), ('rector', 'Ректор')], default='none', max_length=20, verbose_name='Должность')),
                ('working_hours', models.CharField(choices=[('08:00-16:30', '8:00-16:30'), ('08:00-15:00', '8:00-15:00')], default='08:00-16:30', max_length=20, verbose_name='Рабочие часы')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('employment_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('reward', 'Поощрение / Награда'), ('reprimand', 'Выговор')], max_length=15, verbose_name='Тип записи')),
                ('description', models.TextField(verbose_name='Причина / Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
            ],
        ),
    ]
