# Generated by Django 6.1.1 on 2026-09-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dailyattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_status',
            field=models.CharField(choices=[('working', 'Работает'), ('vacation', 'В отпуске'), ('sick', 'На больничном'), ('trip', 'В командировке')], default='working', max_length=20, verbose_name='Статус присутствия'),
        ),
    ]
