# Generated by Django 6.1.1 on 2026-09-20 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_type', models.CharField(choices=[('odd', 'Нечетная неделя (1)'), ('even', 'Четная неделя (2)'), ('both', 'Каждую неделю')], default='both', max_length=10, verbose_name='Тип недели')),
                ('day_of_week', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], max_length=15, verbose_name='День недели')),
                ('time_slot', models.CharField(max_length=20, verbose_name='Время (например, 08:30 - 10:00)')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Дисциплина')),
                ('class_type', models.CharField(max_length=50, verbose_name='Тип (Лекция, Практика, Лаба...)')),
                ('room', models.CharField(max_length=50, verbose_name='Аудитория')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Расписание преподавателей',
                'ordering': ['time_slot'],
            },
        ),
    ]
