# Generated by Django 6.1.1 on 2026-09-11 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='quality_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Минимальная оценка — 1'), django.core.validators.MaxValueValidator(5, message='Максимальная оценка — 5')], verbose_name='Оценка качества (1-5)'),
        ),
    ]
