# Generated by Django 6.1.1 on 2026-09-14 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskreport_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('in_progress', 'В работе'), ('on_review', 'На проверке'), ('completed', 'Выполнена'), ('revision', 'На доработке')], max_length=20, verbose_name='Статус')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время перехода в статус')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выхода из статуса')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='tasks.task')),
            ],
        ),
    ]
